project_id = "joohccchfpcshlihctsm"

[functions.blog-posts]
verify_jwt = false

[functions.blog-sitemap]
verify_jwt = false

[functions.share-blog]
verify_jwt = false

[functions.blog-index]
verify_jwt = false
